config/routes.rb
SimpleTodo::Application.routes.draw do
  root to: "tasks#index"
  resources :tasks, except: [:show]
  put '/tasks/:id/toggle' => "tasks#toggle", as: :toggle_task
 end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, :presence => true

  def toggle_and_give_message
    toggle(:completed)
    save
    completed ? "Task done!" : "Task undone."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to root_path, notice: 'Task was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :ok }
    end
  end

  def toggle
    task = Task.find(params[:id])
    message = task.toggle_and_give_message
    redirect_to root_path, :notice => message
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
# encoding: utf-8
module TasksHelper
  def completed(task)
    task.completed ?
      content_tag(:span, "✔", class: "completed") :
      content_tag(:span, "✖", class: "incomplete")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleTodo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<div id="task-list">
  <input type="search" class="search" placeholder="Filter list" />
  <table>
  <thead>
    <tr>
      <th class="sort" rel="name">Name</th>
      <th class="sort" rel="time">Added</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody class="list">
  <% @tasks.each do |task| %>
    <tr class="task">
      <td>
        <%= completed(task) %>
        <span class="name"><%= task.name %></span>
      </td>
      <td>
        <span class="time hidden"><%= task.created_at.utc.iso8601 %></span>
        <%= distance_of_time_in_words task.created_at, Time.now %> ago
      </td>
      <td class="button"><%= link_to 'Toggle', toggle_task_path(task), method: :put, class: 'btn primary' %></td>
      <td class="button"><%= link_to 'Destroy', task, confirm: 'Are you sure?', method: :delete, class: 'btn danger' %></td>
    </tr>
  <% end %>
  </tbody>
  </table>
</div>

<br />

<%= link_to 'New Task', new_task_path, class: 'btn success' %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>